---
  # top level playbook for creating Users
  # vars set in ../vars/main.yml
  # username = list of users to ensure are on the servers
  # userpass = stored in var/passes.yml and encrypted with Ansible Vault, the password for each new user
  # var/passes.yml default password = examplepassword
  # change the password via `ansible-vault rekey var/passes.yml`

# add users to the targeted servers

- name: ensure these users on the servers
  user:
    name: "{{ item }}"
    password: "{{ userpass }}"
    with_items:
      - "{{ username }}"

- name: ensure users are in the sudo group on the RedHat distro family
  user:
    name: "{{ item }}"
    groups: wheel
    when: ansible_os_family == "RedHat"
  with_items:
    - "{{ username }}"

- name: ensure users are in the sudo group on the Debian distro family
  user:
    name: "{{ item }}"
    groups: sudo
    when: ansible_os_family == "Debian"
  with_items:
    - "{{ username }}"

- name: ensure the users public key is in ~/.ssh/authorized_keys
  copy:
    src: ../files/{{ item }}_id_rsa.pub
    dest: /home/{{ item }}/.ssh/authorized_keys
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: 0600
  with_items:
    - "{{ username }}"
